name: CI/CD workflow

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "./application --check --skip-string-normalization"

